### PR TITLE
Change dependency to dropbox-php-sdk to version ^0.2.2

### LINKED ISSUE #32: plans for NC v 21
Hello,

at the moment, NC v21 RC1 was released, so in the near future, NC21 get stable.
Have you any plans for supporting NC21 with you NC-App?

thanks

### PR DESCRIPTION
**Pull request by fritteli**
Version 0.2.2  of dropbox-php-sdk depends on guzzle ~6.0|~7.0. This is needed to resolve DJaeger/files_external_dropbox#32.

### CODE REVIEW

**Review by Hemant-Mann — APPROVED** [review]

**Comment by Hemant-Mann** [comment]
Hey @fritteli

Thanks for taking the time to create a pull request.

**Comment by fritteli** [comment]
Wow, thank you for merging this so quickly! Do you reckon you could create a new release/tag for this?

**Comment by fritteli** [comment]
Oh, and also update the package on packagist (https://packagist.org/packages/hemant-mann/flysystem-dropbox)? That would be most appreciated! 🙏

**Comment by Hemant-Mann** [comment]
Hey @fritteli 

I've created a new tag https://github.com/Hemant-Mann/flysystem-dropbox/releases/tag/v1.0.4

**Pull request merged**
